angular.module("app").factory("Activity", function (AWSService, UserDataService) {
    // ---Activity class---
    // Generated by actions by caretaker or senior such as "____ picked up groceries" etc.
    class Activity {
        constructor(descriptor) {
            Object.assign(this, {
                id: descriptor.id,
                data: descriptor.data,
                caretakerID: 0,
                date: descriptor.date,
                time: '',
                caretakerName: UserDataService.name,
                type: '',
                logString: ''
            }, descriptor);
        }

        // logs the activity to DynamoDB through the AWSService
        logActivity() {
            AWSService.logActivity(this);
        }
    }

    return Activity;
});
